### PR TITLE
Add `MessageBag::merge()` method

### PR DESCRIPTION
**Pull request by OskarStark**
Or what about naming it `merge()`?

### CODE REVIEW

**Comment by chr-hertel** [comment]
uh, i like `merge` more

**Comment by OskarStark** [comment]
> uh, i like merge more

same same

**Comment by OskarStark** [comment]
Ready to merge

**Review by chr-hertel — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks

**Comment by chr-hertel** [comment]
Thank you Oskar 😍 👍

**Comment by OskarStark** [comment]
> Thank you Oskar 😍 👍

Thank YOU Chris ❤️

**Pull request merged**
