### PR TITLE
Rename `Runtime` to `Platform`

### PR DESCRIPTION
**Pull request by OskarStark**
Refs
* #27 

### Needs (in order)
- [ ] `0.2` release of `php-llm/llm-chain`
- [ ] Merge of https://github.com/php-llm/llm-chain-bundle/pull/20
- [ ] `0.2` release of `php-llm/llm-chain-bundle`
- [ ] Closing of #27

### CODE REVIEW

**Comment by chr-hertel** [comment]
Don't you think it's fine without tagging? don't care too much about semver at this point with 3 users and stating every tag as pre release :D
if you need it for your process, i'm def up for it - but i'm also lazy

**Review by chr-hertel — APPROVED** [review]
reviewed and tested - thank you :pray:

**Comment by chr-hertel** [comment]
Tagged the version :+1:

**Comment by OskarStark** [comment]
> Don't you think it's fine without tagging? don't care too much about semver at this point with 3 users and stating every tag as pre release :D

I agree, but a pipeline for the bundle with lowest and highest would fail otherwise without a new release, right?

**Pull request merged**
