### PR TITLE
feat: introduce message metadata and traits (#91)

### PR DESCRIPTION
**Pull request by chr-hertel**
Multiple ideas around Message - started by #77 

1. i think the traits make it easier for people to build their own messages on top of the interface if needed
2. the metadata are a low structured gimmick that could reduce the need of having custom messages

didn't that anything yet and just a draft ...

### CODE REVIEW

**Comment by OskarStark** [comment]
TBH I am not sure I like this 😄

**Comment by chr-hertel** [comment]
Me neither. What is your concern about?

**Comment by chr-hertel** [comment]
Imagine i would want that UID in all messages, i would need to extend all messages to do so. Custom Systemmessage, CustomAssistantMessage, etc... or when using metadata the data would rather be unstructured

**Comment by chr-hertel** [comment]
And that wouldn't be sufficient since processors, like the Tool one, add built in messages without UID.

But other than UID it could be the actual User reference, additional information about the tool call, like used source documents or links

**Comment by chr-hertel** [comment]
closed in favor of #166 and #174

**Pull request closed without merging**
