### PR TITLE
refactor: `ResponseInterface` as `Chain` return value

### PR DESCRIPTION
**Pull request by chr-hertel**

### CODE REVIEW

**Comment by OskarStark** [comment]
I like this

**Comment by OskarStark** [comment]
I added some tests for your branch here:
* https://github.com/php-llm/llm-chain/pull/120

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
I think we can add `No BC break` label instead of adding `BC break` label 🤣

**Comment by chr-hertel** [comment]
i'm not awake enough for this :D why is it not a BC break?

**Comment by OskarStark** [comment]
I mean we nearly only introduce BC breaks, so maybe its better to opt out 😅

**Comment by chr-hertel** [comment]
true :angel:

**Pull request merged**
